from pydantic import BaseModel
from typing import Optional, List


# What user SENDS when creating
class CommentCreate(BaseModel):
    content: str
    authorId: str
    authorName: str
    parentId: Optional[str] = None


# What API RETURNS 
class CommentResponse(BaseModel):
    id: str              # Generated by DB
    modelId: str         # From URL path
    content: str
    authorId: str
    authorName: str
    isCreator: bool      # Calculated by backend
    parentId: Optional[str]
    createdAt: str       # Generated by backend
    updatedAt: str       # Generated by backend
    replies: List[dict]  # Built by backend (nested comments)


# What user SENDS when updating
class CommentUpdate(BaseModel):
    content: str         # Only thing users can change