# app/repositories/artifacts_repo.py
# -----------------------------------------------------------------------------
# Repository helper functions for the Artifact ORM model.
# These functions encapsulate common DB operations used by the Upload/Download
# service to register and look up stored artifacts (files) in the metadata DB.
#
# Key ideas:
# - Artifacts are identified by a DB primary key, but we also treat
#   (storage_key) and (content_hash, size_bytes) as unique selectors.
# - create_artifact() is idempotent-ish: if an INSERT races with an existing row
#   (e.g., due to concurrent uploads of the same content), we catch the
#   IntegrityError, roll back the failed INSERT, and then return the already
#   existing row instead of crashing.
# - We use db.flush() (not commit) to obtain the generated PK while allowing the
#   caller to compose this write into a larger transaction.
# -----------------------------------------------------------------------------

from typing import Optional
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError

from ..models import Artifact


def create_artifact(
    db: Session,
    *,
    storage_key: str,
    content_hash: str,
    size_bytes: int,
    mime_type: Optional[str] = None,
    owner_id: Optional[str] = None,
) -> Artifact:
    """
    Insert an Artifact row or return the existing one if a uniqueness conflict occurs.

    Parameters
    ----------
    db : Session
        An active SQLAlchemy session (transaction scope controlled by the caller).
    storage_key : str
        The final, permanent object key in the blob store (e.g., S3/MinIO path).
    content_hash : str
        Content-addressable identifier (e.g., SHA-256) used for de-duplication.
    size_bytes : int
        Raw byte size of the artifact; paired with content_hash for uniqueness.
    mime_type : Optional[str]
        Optional MIME type for convenience/filters in the catalog UI.
    owner_id : Optional[str]
        Optional owner/tenant identifier used for RBAC/visibility.

    Returns
    -------
    Artifact
        The newly created row, or the existing row if one already matches
        the unique constraints.

    Notes
    -----
    - Uses db.flush() to obtain a primary key without committing. This lets callers
      batch multiple writes into one commit and keeps this function side-effect
      limited to the current transaction.
    - On IntegrityError (e.g., unique index violation), we:
        1) rollback the failed INSERT
        2) attempt to fetch an existing artifact by storage_key OR by (hash, size)
        3) if found, return it; otherwise re-raise the exception to the caller
    """
    # Create a transient ORM instance with the provided metadata.
    art = Artifact(
        storage_key=storage_key,
        content_hash=content_hash,
        size_bytes=size_bytes,
        mime_type=mime_type,
        owner_id=owner_id,
    )
    # Stage the INSERT in the current transaction.
    db.add(art)
    try:
        # Flush sends the pending INSERT to the DB so autogenerated fields (like PK)
        # are populated on `art` without finalizing the transaction.
        db.flush()  # get PK without full commit (allows composing larger transaction later)
    except IntegrityError:
        # The INSERT likely violated a uniqueness constraint (race with another txn).
        # We must rollback this failed statement before issuing new queries.
        db.rollback()
        # Try fetch existing by unique keys (content_hash + size) or storage_key
        # Order matters only for performance; both checks are functionally equivalent
        # ways to identify the same artifact.
        existing = get_by_storage_key(db, storage_key) or get_by_hash_and_size(
            db, content_hash, size_bytes
        )
        if existing:
            # Return the already-present row to keep create idempotent for callers.
            return existing
        # If we couldn't find an existing row, bubble up the original error so the
        # caller can decide how to handle it (e.g., retry, report 409/500, etc.).
        raise
    # Flush succeeded; return the managed instance (still uncommitted).
    return art


def get(db: Session, artifact_id: str) -> Optional[Artifact]:
    """
    Load an Artifact by its primary key.

    Note: In SQLAlchemy 2.x, Query.get() is considered legacy; Session.get(Model, pk)
    is preferred. We keep Query.get() here to avoid changing behavior/signatures.
    """
    return db.query(Artifact).get(artifact_id)


def get_by_storage_key(db: Session, storage_key: str) -> Optional[Artifact]:
    """
    Look up an Artifact by its storage_key (the permanent blob store key).
    This is useful when the client already knows the final object path.
    """
    return db.query(Artifact).filter(Artifact.storage_key == storage_key).one_or_none()


def get_by_hash_and_size(db: Session, content_hash: str, size_bytes: int) -> Optional[Artifact]:
    """
    Look up an Artifact using content-based identity: (content_hash, size_bytes).
    This complements storage_key lookups and supports deduplication flows.
    """
    return (
        db.query(Artifact)
        .filter(Artifact.content_hash == content_hash, Artifact.size_bytes == size_bytes)
        .one_or_none()
    )
